#!/usr/bin/env bash
# Print the subdomains for a domain

if (($# == 1));
then
	for SUBDOMAIN in "www" "lb-01" "web-01" "web-02";
	do
		RECORD_TYPE=$(dig "$SUBDOMAIN"'.'"$1" | grep -A1 'ANSWER SECTION:' | grep "$SUBDOMAIN"'.'"$1" | awk '{print $4}');
		DESTINATION=$(dig "$SUBDOMAIN"'.'"$1" | grep -A1 'ANSWER SECTION:' | grep "$SUBDOMAIN"'.'"$1" | awk '{print $5}');
		echo "The subdomain '$SUBDOMAIN' is a ""$RECORD_TYPE"" record and points to ""$DESTINATION""";
	done
elif (($# > 1));
then
	RECORD_TYPE=$(dig "$2"'.'"$1" | grep -A1 'ANSWER SECTION:' | grep "$2"'.'"$1" | awk '{print $4}');
	DESTINATION=$(dig "$2"'.'"$1" | grep -A1 'ANSWER SECTION:' | grep "$2"'.'"$1" | awk '{print $5}');
	echo "The subdomain ""$2"" is a ""$RECORD_TYPE"" record and points to ""$DESTINATION""";
fi
