#!/usr/bin/env bash
# install ngnix
sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
