#!/usr/bin/env bash
# install ngnix
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
