#!/usr/bin/env bash
# HTTP 404 error code
apt-get update
apt-get -y install nginx
old="server_name _;"
new="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}\n"
sed -i "/$old/a\\$new" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/Http-404.html
new_error = "\n\terror_page 404 /Http-404.html;"
sed -i "/$old/a\\$new_error" /etc/nginx/sites-available/default
service nginx restart