#!/usr/bin/env bash
# install and Configure HAproxy
apt-get update -y
apt-get install -y haproxy

sudo echo "
frontend main
   bind *:80
   mode http
   default_backend web-server

backend web-server
   balance roundrobin
   server 2718-web-01 35.227.56.113:80 check
   server 2718-web-02 35.229.26.230:80 check
" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
