#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2

done